import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * figmaAssetPlugin
 *
 * Resolves `figma:asset/<hash>.png` virtual imports that are generated by
 * Figma Make's bundler. These do not exist on the local filesystem, so Vite
 * would otherwise throw a "Failed to resolve import" error during `npm run dev`
 * and `npm run build`.
 *
 * Strategy:
 *  - Intercept any module ID that starts with "figma:asset/"
 *  - Return a virtual module that exports a 1×1 transparent PNG data URL
 *  - This keeps all source files identical to the Figma Make environment
 *    while allowing a smooth local dev / CI build
 */
function figmaAssetPlugin() {
  // Smallest valid 1×1 transparent PNG encoded as a data URL
  var TRANSPARENT_PNG =
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';

  // Virtual module prefix — the leading \0 tells Rollup/Vite this is virtual
  var VIRTUAL_PREFIX = '\0figma-asset:';

  return {
    name: 'figma-asset-fallback',
    enforce: 'pre',

    resolveId: function (id) {
      if (id.startsWith('figma:asset/')) {
        // Map  figma:asset/<hash>.png  →  \0figma-asset:<hash>.png
        return VIRTUAL_PREFIX + id.slice('figma:asset/'.length);
      }
      return undefined;
    },

    load: function (id) {
      if (id.startsWith(VIRTUAL_PREFIX)) {
        // Export the placeholder as the default export so
        //   import logo from 'figma:asset/abc123.png'
        // resolves to the data URL string.
        return 'export default "' + TRANSPARENT_PNG + '";';
      }
      return undefined;
    },
  };
}

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [figmaAssetPlugin(), react()],
  base: "./",
  resolve: {
    alias: {
      "@": resolve(__dirname, "./"),
      "@/components": resolve(__dirname, "./components"),
      "@/styles": resolve(__dirname, "./styles"),
      "@/utils": resolve(__dirname, "./utils"),
      "@/data": resolve(__dirname, "./data"),
      "@/hooks": resolve(__dirname, "./hooks"),
    },
  },
  build: {
    outDir: "dist",
    sourcemap: true,
    assetsDir: "assets",
    
    // Performance Optimizations
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
      },
      output: {
        // Optimize chunk naming
        chunkFileNames: 'assets/js/[name]-[hash].js',
        entryFileNames: 'assets/js/[name]-[hash].js',
        assetFileNames: (assetInfo) => {
          // Organize assets by type
          const info = assetInfo.name?.split('.') || [];
          const ext = info[info.length - 1];
          
          if (/png|jpe?g|svg|gif|tiff|bmp|ico/i.test(ext)) {
            return 'assets/images/[name]-[hash][extname]';
          }
          if (/woff2?|eot|ttf|otf/i.test(ext)) {
            return 'assets/fonts/[name]-[hash][extname]';
          }
          return 'assets/[ext]/[name]-[hash][extname]';
        },
      },
    },
    
    // Optimize chunk size warnings
    chunkSizeWarningLimit: 1000, // 1MB warning threshold
    
    // Minification options
    minify: 'terser',
    terserOptions: {
      compress: {
        drop_console: true, // Remove console.log in production
        drop_debugger: true,
      },
      format: {
        comments: false, // Remove all comments
      },
    },
    
    // CSS code splitting
    cssCodeSplit: true,
    
    // Asset inlining threshold (8kb)
    assetsInlineLimit: 8192,
  },
  
  // Optimizations for development
  optimizeDeps: {
    include: [
      'react',
      'react-dom',
      'lucide-react',
    ],
    exclude: [],
  },
  
  server: {
    port: 3000,
    host: true,
  },
  preview: {
    port: 3000,
    host: true,
  },
});